# Generated by Django 4.2.3 on 2024-08-29 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='labour_complaint',
            fields=[
                ('labour_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint', models.CharField(max_length=500, verbose_name='complaint')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.staff')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
