# Generated by Django 4.2.3 on 2024-08-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_labour_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='blacklisted',
            field=models.BooleanField(default=False, verbose_name='blacklisted'),
        ),
    ]
